"""Headless local-runtime process and catalog manager."""

from acta.runtime.errors import (
    CODE_NOT_RUNNING,
    CODE_OK,
    CODE_OOM,
    CODE_PULL_UNCONFIRMED,
    CODE_REMOTE_URL,
    CODE_START_FAILED,
    CODE_STOP_FAILED,
    ERROR_CODES,
    RuntimeManagerError,
    runtime_message_ru,
)
from acta.runtime.manager import (
    CLOUD_FALLBACK_ENABLED,
    DEFAULT_ENDPOINTS,
    CatalogEntry,
    ProcessState,
    PullHook,
    RuntimeKind,
    RuntimeManager,
    RuntimeMetrics,
    RuntimeRunner,
    RuntimeStatus,
    default_endpoint,
    resolve_cloud_fallback,
)
from acta.runtime.profiles import (
    BAND_8_16,
    BAND_16_32,
    BAND_32_64,
    BAND_64_PLUS,
    HARDWARE_PROFILES,
    HardwareProfile,
    recommend_for_ram,
)

__all__ = [
    "BAND_16_32",
    "BAND_32_64",
    "BAND_64_PLUS",
    "BAND_8_16",
    "CLOUD_FALLBACK_ENABLED",
    "CODE_NOT_RUNNING",
    "CODE_OK",
    "CODE_OOM",
    "CODE_PULL_UNCONFIRMED",
    "CODE_REMOTE_URL",
    "CODE_START_FAILED",
    "CODE_STOP_FAILED",
    "DEFAULT_ENDPOINTS",
    "ERROR_CODES",
    "HARDWARE_PROFILES",
    "CatalogEntry",
    "HardwareProfile",
    "ProcessState",
    "PullHook",
    "RuntimeKind",
    "RuntimeManager",
    "RuntimeManagerError",
    "RuntimeMetrics",
    "RuntimeRunner",
    "RuntimeStatus",
    "default_endpoint",
    "recommend_for_ram",
    "resolve_cloud_fallback",
    "runtime_message_ru",
]
