"""Local document ingest with size, path, and zip-bomb guards."""

from mark.documents.errors import (
    CODE_BAD_MIME,
    CODE_MISSING_HOOK,
    CODE_OK,
    CODE_PATH_TRAVERSAL,
    CODE_TOO_LARGE,
    CODE_ZIP_BOMB,
    ERROR_CODES,
    BadMimeError,
    DocumentIngestError,
    DocumentTooLargeError,
    MissingParserHookError,
    PathTraversalError,
    ZipBombError,
    document_message,
)
from mark.documents.guards import (
    ALLOWED_MIMES,
    DEFAULT_MAX_SIZE,
    DEFAULT_MAX_ZIP_RATIO,
    DEFAULT_MAX_ZIP_UNCOMPRESSED,
    EXTENSION_KINDS,
)
from mark.documents.ingestor import (
    AnalyzeImageHook,
    DocumentIngestor,
    ExtractDocxHook,
    ExtractPdfHook,
    TranscribeAudioHook,
)
from mark.documents.types import (
    UNTRUSTED_CLOSE,
    UNTRUSTED_NOTICE,
    UNTRUSTED_OPEN,
    DocumentExtract,
    DocumentKind,
    wrap_untrusted,
)

__all__ = [
    "ALLOWED_MIMES",
    "CODE_BAD_MIME",
    "CODE_MISSING_HOOK",
    "CODE_OK",
    "CODE_PATH_TRAVERSAL",
    "CODE_TOO_LARGE",
    "CODE_ZIP_BOMB",
    "DEFAULT_MAX_SIZE",
    "DEFAULT_MAX_ZIP_RATIO",
    "DEFAULT_MAX_ZIP_UNCOMPRESSED",
    "ERROR_CODES",
    "EXTENSION_KINDS",
    "UNTRUSTED_CLOSE",
    "UNTRUSTED_NOTICE",
    "UNTRUSTED_OPEN",
    "AnalyzeImageHook",
    "BadMimeError",
    "DocumentExtract",
    "DocumentIngestError",
    "DocumentIngestor",
    "DocumentKind",
    "DocumentTooLargeError",
    "ExtractDocxHook",
    "ExtractPdfHook",
    "MissingParserHookError",
    "PathTraversalError",
    "TranscribeAudioHook",
    "ZipBombError",
    "document_message",
    "wrap_untrusted",
]
